// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQoL3yc4QdONYkVD0xRVUQetI8MSVn0o',
    appId: '1:606901887649:web:3ac300ec909f9c79f746e0',
    messagingSenderId: '606901887649',
    projectId: 'final-flutter-b12f7',
    authDomain: 'final-flutter-b12f7.firebaseapp.com',
    storageBucket: 'final-flutter-b12f7.appspot.com',
    measurementId: 'G-H1FBPSL23P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7XdF21ylkj25QTpyKy1VlkqNvbOJMvM',
    appId: '1:606901887649:android:d3290954f6e33b87f746e0',
    messagingSenderId: '606901887649',
    projectId: 'final-flutter-b12f7',
    storageBucket: 'final-flutter-b12f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAibEWN2A_QN0DKrGVMTc5Pt5-BmQ6zpIg',
    appId: '1:606901887649:ios:01b90b476168ee73f746e0',
    messagingSenderId: '606901887649',
    projectId: 'final-flutter-b12f7',
    storageBucket: 'final-flutter-b12f7.appspot.com',
    iosClientId: '606901887649-o969faafeffrvjatesfj6lp3hvtpoav6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalFlutterr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAibEWN2A_QN0DKrGVMTc5Pt5-BmQ6zpIg',
    appId: '1:606901887649:ios:01b90b476168ee73f746e0',
    messagingSenderId: '606901887649',
    projectId: 'final-flutter-b12f7',
    storageBucket: 'final-flutter-b12f7.appspot.com',
    iosClientId: '606901887649-o969faafeffrvjatesfj6lp3hvtpoav6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalFlutterr',
  );
}
